"""add Department

Revision ID: 78599b74ddc9
Revises: 39da8841364d
Create Date: 2024-07-09 13:20:26.749043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78599b74ddc9'
down_revision = '39da8841364d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
